title: Graph Related Conference Deadlines 
# (Maintained by @FinYang)
# email: Fin.Yang@monash.edu
description: Countdowns to graph neural networks and graph signal processing related conference deadlines. 
author: Zepeng Zhang
author_link: https://zepengzhang.com/

domain: "ddl.zepengzhang.com"
baseurl: ""

#twitter_username: YangzhuoranY
#twitter_hashtag:
#github_username: FinYang
#github_repo: ai-deadlines

#ga_id: UA-129140417-2

include: ['_pages']
