title: Data Science and AI Conference Deadlines # (Maintained by @FinYang)
# email: Fin.Yang@monash.edu
description: Countdowns to ML/DM/SP/IT/OPT conference deadlines. 
author: Fin Yang
author_link: https://yangzhuoranyang.com/

domain: "zhaogroup.netlify.app"
baseurl: ""

twitter_username: YangzhuoranY
twitter_hashtag:
github_username: FinYang
github_repo: ai-deadlines

ga_id: UA-129140417-2

include: ['_pages']
